### ISSUE TITLE
Unordered SDP 

### ISSUE THREAD

**Issue by lattice0** [sdroege/sdp-types#6]
On Wikipedia, there is this RTSP example with SDP (https://en.wikipedia.org/wiki/Real_Time_Streaming_Protocol):

```
C->S: DESCRIBE rtsp://example.com/media.mp4 RTSP/1.0
      CSeq: 2

S->C: RTSP/1.0 200 OK
      CSeq: 2
      Content-Base: rtsp://example.com/media.mp4
      Content-Type: application/sdp
      Content-Length: 460

      m=video 0 RTP/AVP 96
      a=control:streamid=0
      a=range:npt=0-7.741000
      a=length:npt=7.741000
      a=rtpmap:96 MP4V-ES/5544
      a=mimetype:string;"video/MP4V-ES"
      a=AvgBitRate:integer;304018
      a=StreamName:string;"hinted video track"
      m=audio 0 RTP/AVP 97
      a=control:streamid=1
      a=range:npt=0-7.712000
      a=length:npt=7.712000
      a=rtpmap:97 mpeg4-generic/32000/2
      a=mimetype:string;"audio/mpeg4-generic"
      a=AvgBitRate:integer;65790
      a=StreamName:string;"hinted audio track"
```

Parsing the SDP part of the response above fails on `sdp-types` because it starts first by parsing the session information, for which `m=video 0 RTP/AVP 96` is invalid (there's no 'm' in the Session part of the SDP), so it returns `Err`. I've just read rfc4566 and indeed, your implementation seems correct, because the specification says 

>    An SDP session description consists of a session-level section
>    followed by zero or more media-level sections.

Do you have any explanation for the wikipedia RTSP dump example? Is it wrong? Could we encounter unordered SDP information on some cameras?

Thank you very much.

**Comment by sdroege** [comment]
It's wrong already because it doesn't start with the `v=0` line, doesn't have the mandatory `o=` and `s=` lines.

The example on wikipedia is simply wrong, I don't know why :) https://en.wikipedia.org/wiki/Session_Description_Protocol has a valid example
